# Hugo config

name = "Essay"
license = "MIT"
licenselink = "https://github.com/sam33r/essay/blob/master/LICENSE.md"
description = "A simple Hugo theme."
homepage = "http://sameerahuja.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Sameer Ahuja"
  homepage = "http://sameerahuja.com"

